### ISSUE TITLE
Editorial: convert HtmlMediaElements to autolinks

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#264] opened 2021-03-03 02:53 UTC
For some reason all of our links to media element attributes/methods are written out, instead of using bikeshed autolinking.  The spec would be easier to edit if we used autolinks instead.

Some attributes like `currentSrc` have multiple definitions in HTML so we need to sort out how to autolink those.  I tried a couple of things and they didn't work.

**Comment by tidoust** [comment] 2021-03-03 09:16
You may need to list most of these definitions explicitly using [Custom Definitions](https://tabatkins.github.io/bikeshed/#custom-dfns) in order to be able to use autolink shortcuts to HTML.

The problem is that the HTML spec does not yet properly follow the [definitions data model](https://tabatkins.github.io/bikeshed/#dfn-contract), so Shepherd (on which Bikeshed currently depends for its definitions database) may not see all of them when it crawls the spec.

**Comment by louaybassbouss** [comment] 2021-03-15 14:48
@mfoltzgoogle  @tidoust I think we can close this issue can you confirm?

**Closed** 2021-03-15 16:35 UTC
Labels: help wanted
